"""initial_migration

Revision ID: ea23779cf0d4
Revises: 
Create Date: 2021-11-21 19:38:31.004975+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea23779cf0d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_item_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('to_do_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_to_do_lists_name'), 'to_do_lists', ['name'], unique=False)
    op.create_table('list_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('list_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=1020), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['to_do_lists.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['list_item_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_items')
    op.drop_index(op.f('ix_to_do_lists_name'), table_name='to_do_lists')
    op.drop_table('to_do_lists')
    op.drop_table('list_item_statuses')
    # ### end Alembic commands ###
